# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Investment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
            ],
            options={
                'db_table': 'Mandate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mandate_Portfolio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Mandate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('activeflag_b', models.BooleanField(db_column='ActiveFlag_B')),
                ('create_d', models.DateField(db_column='Create_D')),
                ('last_modf_d', models.DateField(blank=True, db_column='Last_Modf_D', null=True)),
            ],
            options={
                'db_table': 'Portfolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('positiondatefrom_d', models.DateField(blank=True, db_column='PositionDateFrom_D', null=True)),
                ('positiondateto_d', models.DateField(blank=True, db_column='PositionDateTo_D', null=True)),
                ('quantity_n', models.DecimalField(blank=True, db_column='Quantity_N', decimal_places=10, max_digits=30, null=True)),
                ('price_cost_n', models.DecimalField(blank=True, db_column='Price_Cost_N', decimal_places=2, max_digits=18, null=True)),
                ('price_valuation_kvg_n', models.DecimalField(blank=True, db_column='Price_Valuation_KVG_N', decimal_places=0, max_digits=18, null=True)),
                ('exchangerate_n', models.DecimalField(blank=True, db_column='ExchangeRate_N', decimal_places=4, max_digits=10, null=True)),
                ('market_value_kvg_eur_n', models.DecimalField(blank=True, db_column='Market_Value_KVG_EUR_N', decimal_places=10, max_digits=30, null=True)),
                ('market_value_kvg_fc_n', models.DecimalField(blank=True, db_column='Market_Value_KVG_FC_N', decimal_places=10, max_digits=30, null=True)),
                ('market_data_type_c', models.CharField(db_column='Market_Data_Type_C', max_length=50)),
                ('nominal_value_bond_n', models.DecimalField(blank=True, db_column='Nominal_Value_Bond_N', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity_n', models.DecimalField(blank=True, db_column='Quantity_N', decimal_places=10, max_digits=30, null=True)),
                ('price_n', models.DecimalField(db_column='Price_N', decimal_places=2, max_digits=18)),
                ('exchangerate_n', models.DecimalField(db_column='ExchangeRate_N', decimal_places=4, max_digits=10)),
                ('volumne_eur_n', models.DecimalField(blank=True, db_column='Volume_EUR_N', decimal_places=2, max_digits=18, null=True)),
                ('volume_fc_n', models.DecimalField(blank=True, db_column='Volume_FC_N', decimal_places=2, max_digits=18, null=True)),
                ('tradedate_d', models.DateField(db_column='TradeDate_D')),
                ('valuedate_d', models.DateField(blank=True, db_column='ValueDate_D', null=True)),
                ('createdate_d', models.DateField(blank=True, db_column='CreateDate_D', null=True)),
                ('nominal_value_bond_n', models.DecimalField(blank=True, db_column='Nominal_Value_Bond_N', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
            ],
            options={
                'db_table': 'Type',
                'managed': False,
            },
        ),
    ]
