# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InstrumentDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'Confidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoldingTime',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'HoldingTime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lookback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.IntegerField(db_column='Value')),
            ],
            options={
                'db_table': 'Lookback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persistence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'Persistence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riskfactor_Mapping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Riskfactor_Mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskfactorComposition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('weight_n', models.DecimalField(db_column='Weight_N', decimal_places=4, max_digits=6)),
            ],
            options={
                'db_table': 'RiskfactorComposition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('description_c', models.CharField(db_column='Description_C', max_length=50)),
            ],
            options={
                'db_table': 'RiskModel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riskrawdata',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('creation_dt', models.DateTimeField(db_column='Creation_DT')),
                ('date_d', models.CharField(db_column='Date_D', max_length=10)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'Riskrawdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensitivity_C',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_d', models.CharField(db_column='Date_D', max_length=10)),
                ('creation_dt', models.DateTimeField(db_column='Creation_DT')),
                ('riskfactor_mapping_id', models.IntegerField(db_column='Riskfactor_Mapping_ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'Sensitivity_C',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riskfactor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hedgeinstrument', models.ForeignKey(blank=True, db_column='HedgeInstrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedge_instrument', to='InstrumentDataManagement.Instrument')),
                ('riskfactorinstrument', models.ForeignKey(db_column='RiskfactorInsturment_ID', on_delete=django.db.models.deletion.CASCADE, related_name='riskfactor_instrument', to='InstrumentDataManagement.Instrument')),
            ],
            options={
                'db_table': 'Riskfactor',
            },
        ),
    ]
