# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InstrumentDataManagement', '0001_initial'),
        ('PortfolioPositionManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'Confidence',
            },
        ),
        migrations.CreateModel(
            name='HoldingTime',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'HoldingTime',
            },
        ),
        migrations.CreateModel(
            name='Lookback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.IntegerField(db_column='Value')),
            ],
            options={
                'db_table': 'Lookback',
            },
        ),
        migrations.CreateModel(
            name='Persistence',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
            ],
            options={
                'db_table': 'Persistence',
            },
        ),
        migrations.CreateModel(
            name='Riskfactor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50, null=True)),
                ('hedgeinstrument', models.ForeignKey(blank=True, db_column='HedgeInstrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedge_instrument', to='InstrumentDataManagement.Instrument')),
                ('riskfactorinstrument', models.ForeignKey(db_column='RiskfactorInsturment_ID', on_delete=django.db.models.deletion.CASCADE, related_name='riskfactor_instrument', to='InstrumentDataManagement.Instrument')),
            ],
            options={
                'db_table': 'Riskfactor',
            },
        ),
        migrations.CreateModel(
            name='Riskfactor_Mapping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('portfolio', models.ForeignKey(db_column='Portfolio_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskmapping_portfolio', to='PortfolioPositionManagement.Portfolio')),
                ('reference_instrument', models.ForeignKey(db_column='Reference_Instrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_reference_instrument', to='InstrumentDataManagement.Instrument')),
                ('riskfactor', models.ForeignKey(db_column='Riskfactor_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_riskfactor', to='RiskModelManagement.Riskfactor')),
            ],
            options={
                'db_table': 'Riskfactor_Mapping',
            },
        ),
        migrations.CreateModel(
            name='RiskfactorComposition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('weight_n', models.DecimalField(db_column='Weight_N', decimal_places=4, max_digits=6)),
                ('parent_riskfactor', models.ForeignKey(db_column='Parent_Riskfactor_ID', on_delete=django.db.models.deletion.CASCADE, related_name='composition_reference_riskfactor', to='RiskModelManagement.Riskfactor')),
                ('riskfactor', models.ForeignKey(db_column='Riskfactor_ID', on_delete=django.db.models.deletion.CASCADE, related_name='composition_riskfactor', to='RiskModelManagement.Riskfactor')),
            ],
            options={
                'db_table': 'RiskfactorComposition',
            },
        ),
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('description_c', models.CharField(db_column='Description_C', max_length=50)),
            ],
            options={
                'db_table': 'RiskModel',
            },
        ),
        migrations.CreateModel(
            name='Riskrawdata',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('creation_dt', models.DateTimeField(db_column='Creation_DT')),
                ('date_d', models.CharField(db_column='Date_D', max_length=10)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
                ('confidence', models.ForeignKey(db_column='Confidence_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.Confidence')),
                ('holdingtime', models.ForeignKey(db_column='HoldingTime_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.HoldingTime')),
                ('lookback', models.ForeignKey(db_column='Lookback_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.Lookback')),
                ('persistence', models.ForeignKey(db_column='Persistence_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.Persistence')),
                ('riskfactor', models.ForeignKey(db_column='Riskfactor_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.Riskfactor')),
            ],
            options={
                'db_table': 'Riskrawdata',
            },
        ),
        migrations.CreateModel(
            name='Sensitivity_C',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_d', models.CharField(db_column='Date_D', max_length=10)),
                ('creation_dt', models.DateTimeField(db_column='Creation_DT')),
                ('riskfactor_mapping_id', models.IntegerField(db_column='Riskfactor_Mapping_ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('value', models.DecimalField(db_column='Value', decimal_places=3, max_digits=18)),
                ('lookback', models.ForeignKey(db_column='Lookback_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.Lookback')),
                ('persistence', models.ForeignKey(db_column='Persistence_ID', on_delete=django.db.models.deletion.CASCADE, to='RiskModelManagement.Persistence')),
            ],
            options={
                'db_table': 'Sensitivity_C',
            },
        ),
    ]
