# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentDataManagement', '0001_initial'),
        ('RiskModelManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactor_mapping',
            name='test_decimal_n',
            field=models.DecimalField(db_column='Test_Decimal_N', decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='riskfactor_mapping',
            name='test_instrument',
            field=models.ForeignKey(db_column='Test_Instrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_test_instrument', to='InstrumentDataManagement.Instrument'),
        ),
    ]
