# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskModelManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactor',
            name='name_c',
            field=models.CharField(db_column='Name_C', max_length=50, null=True),
        ),
    ]
