# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiskModelManagement', '0002_auto_20161214_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfactor_mapping',
            name='test_decimal_n',
        ),
        migrations.RemoveField(
            model_name='riskfactor_mapping',
            name='test_instrument',
        ),
    ]
