# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskModelManagement', '0003_auto_20161214_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactor_mapping',
            name='test_decimal_n',
            field=models.DecimalField(db_column='Test_Decimal_N', decimal_places=6, max_digits=12, null=True),
        ),
    ]
