# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiskModelManagement', '0004_riskfactor_mapping_test_decimal_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfactor_mapping',
            name='test_decimal_n',
        ),
    ]
