# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentDataManagement', '0001_initial'),
        ('MarketDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData_Currency_Bloomberg_C',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date_D', null=True)),
                ('px_last', models.DecimalField(db_column='PX_LAST', decimal_places=6, max_digits=12, null=True)),
                ('instrument', models.ForeignKey(db_column='Instrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='InstrumentDataManagement.Instrument')),
            ],
            options={
                'db_table': 'MarketData_Currency_Bloomberg_C',
            },
        ),
        migrations.CreateModel(
            name='MarketData_Currency_C',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date_D', null=True)),
                ('intraday_price_n', models.DecimalField(db_column='Intraday_Price_n', decimal_places=6, max_digits=12, null=True)),
                ('eod_price_n', models.DecimalField(db_column='EOD_Price_n', decimal_places=6, max_digits=12, null=True)),
                ('eod_log_return_n', models.FloatField(db_column='EOD_Log_Return_N', null=True)),
                ('intra_log_return_n', models.FloatField(db_column='Intra_Log_Return_N', null=True)),
                ('instrument', models.ForeignKey(db_column='Instrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='InstrumentDataManagement.Instrument')),
            ],
            options={
                'db_table': 'MarketData_Currency_C',
            },
        ),
        migrations.CreateModel(
            name='MarketData_Currency_DataStream_C',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date_D', null=True)),
                ('instrument', models.ForeignKey(db_column='Instrument_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='InstrumentDataManagement.Instrument')),
            ],
            options={
                'db_table': 'MarketData_Currency_DataStream_C',
            },
        ),
        migrations.AlterUniqueTogether(
            name='marketdata_currency_datastream_c',
            unique_together=set([('instrument', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata_currency_c',
            unique_together=set([('instrument', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata_currency_bloomberg_c',
            unique_together=set([('instrument', 'date')]),
        ),
    ]
