# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('denomination_c', models.CharField(blank=True, db_column='Denomination_C', max_length=50, null=True)),
                ('level_n', models.IntegerField(db_column='Level_N')),
            ],
            options={
                'managed': False,
                'db_table': 'AssetClass',
            },
        ),
        migrations.CreateModel(
            name='AssetClass_Instrument',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'AssetClass_Instrument',
            },
        ),
        migrations.CreateModel(
            name='Codification',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('denomination_c', models.CharField(blank=True, db_column='Denomination_C', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Codification',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('isocode_c', models.CharField(db_column='ISOCode_C', max_length=3)),
                ('denomination_c', models.CharField(blank=True, db_column='Denomination_C', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('isocode_c', models.CharField(db_column='ISOCode_C', max_length=3)),
                ('denomination_c', models.CharField(blank=True, db_column='Denomination_C', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('denomination_c', models.CharField(blank=True, db_column='Denomination_C', max_length=100, null=True)),
                ('multiplier_n', models.DecimalField(blank=True, db_column='Multiplier_N', decimal_places=3, max_digits=10, null=True)),
                ('expiry_d', models.DateField(blank=True, db_column='Expiry_d', null=True)),
                ('contract_forward_rate_n', models.DecimalField(blank=True, db_column='Contract_Forward_Rate_N', decimal_places=3, max_digits=10, null=True)),
                ('maturity_n', models.DecimalField(blank=True, db_column='Maturity_N', decimal_places=3, max_digits=10, null=True)),
                ('bpv_n', models.DecimalField(blank=True, db_column='BPV_N', decimal_places=3, max_digits=12, null=True)),
                ('strike_n', models.DecimalField(blank=True, db_column='Strike_N', decimal_places=3, max_digits=10, null=True)),
                ('main_instrument_b', models.BooleanField(db_column='Main_Instrument_B')),
            ],
            options={
                'managed': False,
                'db_table': 'Instrument',
            },
        ),
        migrations.CreateModel(
            name='Instrumentsynonym',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('validity_d', models.DateField(blank=True, db_column='Validity_D', default=False, null=True)),
                ('code_c', models.CharField(db_column='Code_C', max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'InstrumentSynonym',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('iso_code_c', models.CharField(db_column='ISO_Code_C', max_length=3)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('denomination_c', models.CharField(blank=True, db_column='Denomination_C', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Market',
            },
        ),
        migrations.CreateModel(
            name='Marketdatatype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_c', models.CharField(db_column='Name_C', max_length=50)),
                ('type_c', models.CharField(db_column='Type_C', max_length=50)),
            ],
            options={
                'db_table': 'MarketDataType',
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('instrument', models.OneToOneField(db_column='instrument_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='InstrumentDataManagement.Instrument')),
                ('nominal_n', models.DecimalField(blank=True, db_column='nominal_n', decimal_places=6, max_digits=12, null=True)),
                ('life_n', models.DecimalField(blank=True, db_column='life_n', decimal_places=6, max_digits=12, null=True)),
                ('coupon_current_n', models.DecimalField(blank=True, db_column='coupon_current_n', decimal_places=6, max_digits=12, null=True)),
                ('coupon_floating_n', models.DecimalField(blank=True, db_column='coupon_floating_n', decimal_places=6, max_digits=12, null=True)),
                ('floating_real_margin_n', models.DecimalField(blank=True, db_column='floating_real_margin_n', decimal_places=6, max_digits=12, null=True)),
                ('amortisationtype_c', models.CharField(db_column='amortisationtype_c', max_length=50)),
                ('bondtype_c', models.CharField(db_column='bondtype_c', max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'Bond',
            },
        ),
        migrations.AlterUniqueTogether(
            name='marketdatatype',
            unique_together=set([('name_c',)]),
        ),
    ]
